let nome = 'cauã';
let endereco = 'Marechal Cândido Rondon';
let cachorro1 = 'spike';
let cachorro2 = 'bravinho';
let cachorro3 = 'mel';
console.log(`o nome do cachorro1 é ${cachorro1}`);
console.log(`o nome do cachorro2 é ${cachorro2}`);
console.log(`o nome do cachorro3 é ${cachorro3}`);
console.log(`o nome do aluno  é ${nome}`);
console.log(`o endereço do aluno è ${endereco}`);
